
class Image:
    def __init__(self, *args, **kwargs) -> None: ...
    @staticmethod
    def new_from_file(filename: str, access: str) -> Image: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    def crop(self, left: int, top: int, width: int, height: int) -> Image: ...
    def write_to_file(self, filename: str) -> None: ...
